name: Release CLI

on:
  push:
    branches:
    - release/cli-*

jobs:
  build_test_package:
    name: Build, test and package
    strategy:
      matrix:
        os: [ 'windows-latest' ]
        node: [ 10 ]
        dotnet: [ '3.1.402' ]
        targetFramework: [ 'netcoreapp3.1' ]
        runtime: [ 'win-x64', 'linux-x64', 'osx-x64' ]

    runs-on: ${{ matrix.os }}

    steps:
    # - name: Check event payload
    #   if: steps.release.outputs.module == 'cli' && ((matrix.targetFramework == 'net461' && matrix.runtime == 'win-x64') || matrix.targetFramework == 'netcoreapp3.1')
    #   shell: pwsh
    #   run: |
    #     echo ${{ toJSON(github.event) }}

    - name: Set release module and version
      id: release
      shell: pwsh
      run: |
        $branch = "${{ github.event.ref }}" -replace "refs/heads/release/", ""
        $segments = $branch -split "-"
        $module = $segments[0]
        $version = $segments[1]

        # echo "::set-env name=RELEASE_MODULE::$module"
        # echo "::set-env name=RELEASE_VERSION::$version"

        echo "::set-output name=module::$module"
        echo "::set-output name=version::$version"

    - name: Check release module and version
      if: steps.release.outputs.module == 'cli'
      shell: pwsh
      run: |
        # echo "env: $env:RELEASE_MODULE"
        # echo "env: $env:RELEASE_VERSION"

        echo "output: ${{ steps.release.outputs.module }}"
        echo "output: ${{ steps.release.outputs.version }}"

    - name: Checkout the repository
      if: steps.release.outputs.module == 'cli'
      uses: actions/checkout@v2

    # - name: Setup node.js
    #   if: steps.release.outputs.module == 'cli'
    #   uses: actions/setup-node@v1
    #   with:
    #     node-version: ${{ matrix.node }}

    # - name: Setup .NET SDK
    #   if: steps.release.outputs.module == 'cli'
    #   uses: actions/setup-dotnet@v1
    #   with:
    #     dotnet-version: ${{ matrix.dotnet }}

    - name: Setup .NET SDK 2.1 LTS
      if: steps.release.outputs.module == 'cli'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.1.x'

    - name: Setup .NET SDK 3.1 LTS
      if: steps.release.outputs.module == 'cli'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'

    # - name: Add MSBuild to PATH
    #   if: steps.release.outputs.module == 'cli'
    #   uses: microsoft/setup-msbuild@v1.0.0

    - name: Restore NuGet packages
      if: steps.release.outputs.module == 'cli'
      shell: pwsh
      run: |
        dir
        dotnet restore .

    - name: Build solution
      if: steps.release.outputs.module == 'cli'
      shell: pwsh
      run: |
        dir
        dotnet build . -c Release -p:Version=${{ steps.release.outputs.version }} -v minimal

    - name: Test solution
      if: steps.release.outputs.module == 'cli'
      shell: pwsh
      run: |
        dir
        dotnet test . -c Release

    - name: Publish CLI for .NET Core
      if: steps.release.outputs.module == 'cli'
      shell: pwsh
      run: |
        dir
        dotnet publish ./src/Microsoft.Azure.WebJobs.Extensions.OpenApi.CLI -c Release -f ${{ matrix.targetFramework }} -r ${{ matrix.runtime }} -p:PublishSingleFile=true --self-contained true

    - name: List Package for OpenApi.CLI
      if: steps.release.outputs.module == 'cli'
      shell: pwsh
      run: |
        $sourcepath = "./src/*.OpenApi.CLI/bin/Release/${{ matrix.targetFramework }}/${{ matrix.runtime }}/publish"
        $targetpath = "./src/*.OpenApi.CLI/bin/Release/${{ matrix.targetFramework }}/azfuncopenapi-v${{ steps.release.outputs.version }}-${{ matrix.targetFramework }}-${{ matrix.runtime }}.zip"
        $package = Get-ChildItem -Path $sourcepath -Recurse | Compress-Archive -DestinationPath $targetpath
        $path = (Get-Item $targetpath).FullName
        $name = (Get-Item $targetpath).Name

        echo "::set-env name=PACKAGE_PATH::$path"
        echo "::set-env name=PACKAGE_NAME::$name"

    - name: Check package path and name
      if: steps.release.outputs.module == 'cli'
      id: package
      shell: pwsh
      run: |
        echo "package-path: $env:PACKAGE_PATH"
        echo "package-name: $env:PACKAGE_NAME"

        echo "::set-output name=path::$env:PACKAGE_PATH"
        echo "::set-output name=name::$env:PACKAGE_NAME"

    - name: Upload artifacts
      if: steps.release.outputs.module == 'cli'
      uses: actions/upload-artifact@v2
      with:
        name: cli
        path: "${{ steps.package.outputs.path }}"

  package_release:
    name: Release packages
    needs: build_test_package
    strategy:
      matrix:
        os: [ 'ubuntu-latest' ]
        node: [ 10 ]
        dotnet: [ '3.1.402' ]
        # targetFramework: [ 'net461', 'netcoreapp3.1' ]
        # runtime: [ 'win-x64', 'linux-x64', 'osx-x64' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: cli
        path: artifacts

    - name: Get all artifacts
      id: package
      shell: pwsh
      run: |
        dir ./artifacts

        $packages = Get-ChildItem -Path ./artifacts

        $package0 = $packages[0].Name
        $package1 = $packages[1].Name
        $package2 = $packages[2].Name
        $package3 = $packages[3].Name

        $version = $packages[0].Name.Split('-')[1].Replace("v", "")

        echo "version: $version"
        echo "package0: $package0"
        echo "package1: $package1"
        echo "package2: $package2"
        echo "package3: $package3"

        echo "::set-output name=version::$version"
        echo "::set-output name=package0::$package0"
        echo "::set-output name=package1::$package1"
        echo "::set-output name=package2::$package2"
        echo "::set-output name=package3::$package3"

    - name: Repackage CLI for Linux and MacOS
      shell: bash
      run: |
        unzip "./artifacts/${{ steps.package.outputs.package1 }}" -d "./artifacts/linux"
        chmod +x ./artifacts/linux/azfuncopenapi
        ls -al ./artifacts/linux
        rm "./artifacts/${{ steps.package.outputs.package1 }}"
        zip -r -j "./artifacts/${{ steps.package.outputs.package1 }}" "./artifacts/linux"

        unzip "./artifacts/${{ steps.package.outputs.package2 }}" -d "./artifacts/osx"
        chmod +x ./artifacts/osx/azfuncopenapi
        ls -al ./artifacts/osx
        rm "./artifacts/${{ steps.package.outputs.package2 }}"
        zip -r -j "./artifacts/${{ steps.package.outputs.package2 }}" "./artifacts/osx"

        ls -al ./artifacts

    - name: Create Release to GitHub
      id: ghrelease
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: "cli-${{ steps.package.outputs.version }}"
        release_name: Release "cli-v${{ steps.package.outputs.version }}"
        draft: false
        prerelease: false

    - name: Upload CLI to GitHub - netcoreapp3.1 linux-x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.ghrelease.outputs.upload_url }}
        asset_path: "artifacts/${{ steps.package.outputs.package1 }}"
        asset_name: ${{ steps.package.outputs.package1 }}
        asset_content_type: application/zip

    - name: Upload CLI to GitHub - netcoreapp3.1 osx-x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.ghrelease.outputs.upload_url }}
        asset_path: "artifacts/${{ steps.package.outputs.package2 }}"
        asset_name: ${{ steps.package.outputs.package2 }}
        asset_content_type: application/zip

    - name: Upload CLI to GitHub - netcoreapp3.1 win-x64
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.ghrelease.outputs.upload_url }}
        asset_path: "artifacts/${{ steps.package.outputs.package3 }}"
        asset_name: ${{ steps.package.outputs.package3 }}
        asset_content_type: application/zip

    # - name: Release to npm
    #   uses: JS-DevTools/npm-publish@v1
    #   with:
    #     token: ${{ secrets.NPM_TOKEN }}
    #     package: "./src/*.OpenApi.CLI/package.json"
