name: Build and Test

on:
  push:
    branches:
    - main
    - dev
    - feature/*

jobs:
  build_and_test:
    name: Build and test
    strategy:
      matrix:
        os: [ 'windows-latest' ]
        dotnet: [ '3.1.401' ]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Restore NuGet packages
      shell: pwsh
      run: |
        dir
        dotnet restore .

    - name: Build solution
      shell: pwsh
      run: |
        dir
        dotnet build . -c Debug -v minimal

    - name: Test solution
      shell: pwsh
      run: |
        dir
        dotnet test . -c Debug
